version: "3.9"

services:
  db:
    image: "labring/mssql-server:2022-latest-arm64"
    volumes:
      - ./db_data:/var/opt/mssql/data
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Surbhi08@"
      ACCEPT_EULA: "Y"
